### ISSUE TITLE
Error while building goanalyzer

### ISSUE THREAD

**Issue by sidheshdivekar29** [robaho/goanalyzer#1]
~/workspace/goanalyzer/cmd/goanalyzer$ go build
annotations.go:10:2: use of internal package github.com/robaho/goanalyzer/cmd/goanalyzer/internal/trace not allowed

**Comment by robaho** [comment]
I rebuilt tonight using Go 1.15 and it built and ran fine, so something is wrong with your setup.

I used:

```
export GOROOT=/usr/local/Cellar/go/1.15/libexec #gosetup
export GOPATH=/Users/robertengels/go #gosetup
cd /Users/robertengels/go/src/github.com/robaho/goanalyzer/cmd/goanalyzer
go build -a
```
